---
- name: Add custom Suricata rule and update suricata.yaml
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules file exists
      file:
        path: "/etc/suricata/rules/custom.rules"
        state: touch  
        mode: '0644'

    # Add the custom rule to the file
    - name: Add the custom rule to the custom.rules file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'

    # Ensure 'custom.rules' is in the suricata.yaml rule-files section
    - name: Add 'custom.rules' to rule-files in suricata.yaml
      lineinfile:
        path: /etc/suricata/suricata.yaml
        regexp: '^\s*rule-files:\s*$'  # Match the line 'rule-files:'
        insertafter: '^\s*rule-files:\s*$'
        line: "    - custom.rules"  # Correct indentation for YAML
      notify: Restart Suricata

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
  
