---
- name: Add custom Suricata rule
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Create or update the custom rules file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        mode: '0644'
      vars:
        custom_rule: "{{ custom_rule }}"  # Ensure this variable is passed in correctly
