- name: Add custom Suricata rule
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Add the custom rule to the file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'
