---
- name: Add custom Suricata rule and update suricata.yaml
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Add the custom rule to the file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'

    - name: Add custom rules file to suricata.yaml under rule-files
      lineinfile:
        path: "/etc/suricata/suricata.yaml"
        regexp: '^  - /etc/suricata/rules/custom.rules'
        line: '  - /etc/suricata/rules/custom.rules'
        state: present
        insertafter: '^  rule-files:'

    - name: Ensure the file permissions are correct for custom rule file
      file:
        path: "/etc/suricata/rules/custom.rules"
        mode: '0644'

    - name: Ensure the file permissions are correct for suricata.yaml
      file:
        path: "/etc/suricata/suricata.yaml"
        mode: '0644'
