- name: Add custom Suricata rule and update suricata.yaml
  hosts: all
  become: yes
  tasks:
    # Ensure the custom rules file exists
    - name: Ensure the custom rules file exists
      file:
        path: "/etc/suricata/rules/custom.rules"
        state: touch  
        mode: '0644'

    # Add the custom rule to the file
    - name: Add the custom rule to the custom.rules file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'

    # Ensure 'custom.rules' is added to rule-files in suricata.yaml without removing other entries
    - name: Add 'custom.rules' to rule-files in suricata.yaml
      blockinfile:
        path: /etc/suricata/suricata.yaml
        marker: "# CUSTOM RULE-FILES"
        block: |
          - custom.rules
      notify: Restart Suricata

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
