- name: Add custom Suricata rule and update suricata.yaml
  hosts: all
  become: yes
  tasks:
    # Ensure the custom rules file exists
    - name: Ensure the custom rules file exists
      file:
        path: "/etc/suricata/rules/custom.rules"
        state: touch  
        mode: '0644'

    # Add the custom rule to the file
    - name: Add the custom rule to the custom.rules file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'

    # Replace rule-files section in suricata.yaml
    - name: Update rule-files in suricata.yaml with custom.rules
      blockinfile:
        path: /etc/suricata/suricata.yaml
        marker: "# CUSTOM RULE-FILES"
        block: |
          rule-files:
            - suricata.rules
            - custom.rules
        create: yes
        insertafter: '^rule-files:'

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
