---
- name: Add custom Suricata rule and update suricata.yaml
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules file exists
      file:
        path: "/etc/suricata/rules/custom.rules"
        state: touch  
        mode: '0644'

    - name: Add the custom rule to the file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        line: "{{ custom_rule }}"
        create: yes
        insertafter: EOF
        mode: '0644'

  
