---
- name: Change Interface on suricata.yaml
  hosts: all
  become: true
  vars:
    interface: "{{ lookup('env', 'interface') | default('eth0', true) }}"  # Fallback to 'eth0' if env variable is not set

  tasks:
    - name: Replace all occurrences of interface with the desired value
      lineinfile:
        path: /etc/suricata/suricata.yaml
        regexp: '^\s*-\s*interface:\s*.*$'  # Match lines starting with `- interface:`
        line: '  - interface: {{ interface }}'  # Replace with the correct interface value
      notify: Restart Suricata

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
