- name: Change Interface on suricata.yaml
  hosts: all
  become: true
  vars:
    interface: "{{ lookup('env', 'interface') | default('eth0', true) }}"  # Fallback to 'eth0' if env variable is not set

  tasks:
    - name: Replace all occurrences of interface with the desired value
      replace:
        path: /etc/suricata/suricata.yaml
        regexp: '^\s*-\s*interface:\s*\w+'
        replace: '  - interface: {{ interface }}'
      notify: Restart Suricata

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
