---
- name: Delete custom Suricata rule
  hosts: all
  become: yes
  tasks:
    - name: Debug custom rule
      debug:
        msg: "Custom rule to delete: {{ custom_rule }}"

    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Remove the custom rule from the file using lineinfile with regex
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        regexp: "{{ custom_rule | regex_escape }}"
        state: absent
        mode: '0644'

    - name: Ensure the file permissions are correct
      file:
        path: "/etc/suricata/rules/custom.rules"
        mode: '0644'
