---
- name: Delete custom Suricata rule
  hosts: all
  become: yes
  tasks:
    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Remove the custom rule from the file
      lineinfile:
        path: "/etc/suricata/rules/custom.rules"
        regexp: "{{ custom_rule }}"
        state: absent
        mode: '0644'
