---
- name: Delete custom Suricata rule
  hosts: all
  become: yes
  tasks:
    - name: Debug custom rule
      debug:
        msg: "Custom rule to delete: {{ custom_rule }}"

    - name: Ensure the custom rules directory exists
      file:
        path: "/etc/suricata/rules"
        state: directory
        mode: '0755'

    - name: Remove the custom rule from the file using blockinfile
      blockinfile:
        path: "/etc/suricata/rules/custom.rules"
        block: |
          {{ custom_rule }}
        state: absent

    - name: Ensure the file permissions are correct
      file:
        path: "/etc/suricata/rules/custom.rules"
        mode: '0644'
