---
- name: Fetch fast.log from remote server
  hosts: all
  tasks:
    - name: Ensure destination directory exists
      become: yes
      file:
        path: ~/var/log/suricata/fast.log
        state: directory
    - name: Fetch fast.log file
      become: yes
      fetch:
        src: /var/log/suricata/fast.log
        dest: "{{ ansible_env.HOME }}/ansible_projeto1/"
        flat: yes

