---
- name: Install and configure Suricata
  hosts: all
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Suricata and dependencies
      apt:
        name:
          - suricata
          - suricata-update
        state: present

    - name: Install Suricata rules
      command: suricata-update

    - name: Update Suricata interface configuration
      replace:
        path: /etc/suricata/suricata.yaml
        regexp: '^  - interface:.*$'
        replace: '  - interface: enp0s3'
      notify: Restart Suricata

    - name: Verify Suricata installation (check version)
      command: suricata -V
      register: suricata_version
      changed_when: false
      failed_when: false

    - name: Show Suricata version
      debug:
        msg: "Suricata version: {{ suricata_version.stdout }}"

    - name: Enable and start Suricata service
      service:
        name: suricata
        enabled: yes
        state: started

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
