---
- name: Install and configure Suricata
  hosts: all
  become: true
  vars:
    interface: "{{ lookup('env', 'interface') }}"  # Lookup the interface from environment variable

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Suricata and dependencies
      apt:
        name:
          - suricata
          - suricata-update
        state: present

    - name: Install Suricata rules
      command: suricata-update

    #- name: Replace all occurrences of interface eth0 in the file
    #  lineinfile:
    #    path: /etc/suricata/suricata.yaml
    #    regexp: 'interface:\s*eth0'  # Match the interface eth0 line
    #    replace: 'interface: {{ interface }}'  # Replace with the provided interface variable~
    #    insertafter: 'af-packet:'
    #  notify: Restart Suricata


    - name: Replace default rule path in Suricata config
      lineinfile:
        path: /etc/suricata/suricata.yaml
        regexp: '^#?\s*default-rule-path:.*'
        line: 'default-rule-path: /var/lib/suricata/rules'
        owner: root
        group: root
        mode: 0644
      notify: Restart Suricata

    - name: Verify Suricata installation (check version)
      command: suricata -V
      register: suricata_version
      changed_when: false
      failed_when: false

    - name: Show Suricata version
      debug:
        msg: "Suricata version: {{ suricata_version.stdout }}"

    - name: Run Suricata configuration test
      command: suricata -T
      register: suricata_test
      changed_when: false
      failed_when: suricata_test.rc != 0
      ignore_errors: yes

    - name: Show Suricata config test result
      debug:
        msg: "Suricata config test result: {{ suricata_test.stdout }}"

    - name: Enable and start Suricata service
      service:
        name: suricata
        enabled: yes
        state: started

  handlers:
    - name: Restart Suricata
      service:
        name: suricata
        state: restarted
