---
- name: Verify root's authorized_keys contents
  hosts: all
  become: yes  # Run tasks as root
  vars:
    ssh_key_path: "/root/.ssh/authorized_keys"

  tasks:
    - name: Check if the authorized_keys file exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_keys_stat

    - name: Read the contents of the authorized_keys file if it exists
      command: cat "{{ ssh_key_path }}"
      register: ssh_authorized_keys_contents
      when: ssh_keys_stat.stat.exists
      ignore_errors: yes

    - name: Show the contents of the authorized_keys file
      debug:
        msg: "{{ ssh_authorized_keys_contents.stdout }}"
      when: ssh_keys_stat.stat.exists

    - name: Notify if the authorized_keys file does not exist
      debug:
        msg: "No authorized_keys file found for root."
      when: not ssh_keys_stat.stat.exists
