- name: Verify and manage SSH key contents
  hosts: all
  become: yes
  vars:
    ssh_key_path: "{{ ssh_key_path }}"  # Use the passed variable

  tasks:
    - name: Check if the authorized_keys file exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_keys_stat

    - name: Show the contents of the authorized_keys file
      command: cat "{{ ssh_key_path }}"
      register: ssh_authorized_keys_contents
      when: ssh_keys_stat.stat.exists

    - name: Display the contents of the authorized_keys file
      debug:
        msg: "{{ ssh_authorized_keys_contents.stdout }}"
      when: ssh_keys_stat.stat.exists
