---
- name: List contents of the ~/.ssh/authorized_keys file
  hosts: all
  become: yes  
  vars:
    ssh_key_path: "/home/tomas/.ssh/authorized_keys"
  tasks:
    - name: Check if the authorized_keys file exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_keys_stat

    - name: List the contents of the authorized_keys file if it exists
      shell: cat "{{ ssh_key_path }}"
      register: ssh_authorized_keys_contents
      when: ssh_keys_stat.stat.exists
      ignore_errors: yes

    - name: Show the contents of the authorized_keys file
      debug:
        msg: "{{ ssh_authorized_keys_contents.stdout }}"
      when: ssh_keys_stat.stat.exists
      ignore_errors: yes

    - name: Notify if the authorized_keys file does not exist
      debug:
        msg: "No authorized_keys file found."
      when: not ssh_keys_stat.stat.exists
