---
- name: List contents of the ~/.ssh/authorized_keys file
  hosts: all
  become: yes  
  tasks:
    - name: List the contents of ~/.ssh/authorized_keys
      command: cat ~/.ssh/authorized_keys
      register: ssh_authorized_keys_contents
      ignore_errors: yes

    - name: Show the contents of ~/.ssh/authorized_keys
      debug:
        msg: "{{ ssh_authorized_keys_contents.stdout }}"
