---
- name: Read Suricata fast.log file
  hosts: all
  become: true
  tasks:
    - name: Check if fast.log exists
      stat:
        path: /var/log/suricata/fast.log
      register: fast_log_stat

    - name: Display fast.log content if it exists
      shell: cat /var/log/suricata/fast.log
      when: fast_log_stat.stat.exists
      register: fast_log_contents
      changed_when: false

    - name: Output fast.log content
      debug:
        msg: |
          Fast.log Content:
          {{ fast_log_contents.stdout }}
      when: fast_log_stat.stat.exists

    - name: Error message if fast.log does not exist
      debug:
        msg: "Error: fast.log file not found."
      when: not fast_log_stat.stat.exists
