---
- name: Read and filter Suricata fast.log file
  hosts: all
  become: true
  tasks:
    - name: Check if fast.log exists
      stat:
        path: /var/log/suricata/fast.log
      register: fast_log_stat

    - name: Filter fast.log by date or IP
      shell: |
        if [[ -n "{{ log_date }}" ]]; then
          grep "{{ log_date }}" /var/log/suricata/fast.log
        elif [[ -n "{{ log_ip }}" ]]; then
          grep "{{ log_ip }}" /var/log/suricata/fast.log
        else
          cat /var/log/suricata/fast.log
        fi
      when: fast_log_stat.stat.exists
      register: filtered_logs
      changed_when: false

    - name: Output filtered fast.log content
      debug:
        msg: |
          Filtered Log Content:
          {{ filtered_logs.stdout }}
      when: fast_log_stat.stat.exists

    - name: Error message if fast.log does not exist
      debug:
        msg: "Error: fast.log file not found."
      when: not fast_log_stat.stat.exists
