- name: Read and filter Suricata fast.log file
  hosts: all
  become: true
  vars:
    log_date: "{{ log_date | default('') }}"
    log_ip: "{{ log_ip | default('') }}"
  tasks:
    - name: Debug log_date and log_ip
      debug:
        msg: "log_date: {{ log_date }}, log_ip: {{ log_ip }}"

    - name: Check if fast.log exists
      stat:
        path: /var/log/suricata/fast.log
      register: fast_log_stat

    - name: Filter fast.log by date and IP
      shell: |
        grep "{{ log_date }}" /var/log/suricata/fast.log {% if log_ip != '' %} | grep "{{ log_ip }}" {% endif %}
      when: fast_log_stat.stat.exists
      register: filtered_logs

    - name: Output filtered logs
      debug:
        msg: |
          Filtered Logs:
          {{ filtered_logs.stdout }}
      when: fast_log_stat.stat.exists

    - name: Error message if fast.log does not exist
      debug:
        msg: "Error: fast.log file not found."
      when: not fast_log_stat.stat.exists
