---
- name: Read Suricata fast.log file
  hosts: all
  become: true
  tasks:
    - name: Check if fast.log exists
      stat:
        path: /var/log/suricata/fast.log
      register: fast_log_stat

    - name: Cat the Suricata fast.log file if it exists
      command: cat /var/log/suricata/fast.log
      when: fast_log_stat.stat.exists
      register: fast_log_contents

    - name: Display fast.log content if it exists
      debug:
        msg: "{{ fast_log_contents.stdout }}"
      when: fast_log_stat.stat.exists

    - name: Error message if fast.log does not exist
      debug:
        msg: "Error: fast.log file not found."
      when: not fast_log_stat.stat.exists

