---
- name: View custom Suricata rules
  hosts: all
  become: yes
  tasks:
    - name: Display custom rules file
      command: cat /etc/suricata/rules/custom.rules
      register: custom_rules
    - name: Output custom rules content
      debug:
        var: custom_rules.stdout
        - name: Check if custom rules file exists
          stat:
          path: /etc/suricata/rules/custom.rules
          register: custom_rules_file

        - name: Create custom rules file if it does not exist
          file:
          path: /etc/suricata/rules/custom.rules
          state: touch
          when: not custom_rules_file.stat.exists
