---
- name: View custom Suricata rules
  hosts: all
  become: yes
  tasks:
    - name: Display custom rules file
      command: cat /etc/suricata/rules/custom.rules
      register: custom_rules
    - name: Output custom rules content
      debug:
        var: custom_rules.stdout
